# Exploration initiale des données (EDA - partie 1)

**Datasets :**
- CIC-IDS-2017 : `FridayWorkingHoursAfternoonDDos.pcap_ISCX.csv`
- UNSW-NB15 : `UNSW-NB15_1.csv`
- Cybersecurity Threat Detection Logs : `cybersecurity_threat_detection_logs.csv`

Charger les datasets et analyser leur structure (lignes, colonnes, types, valeurs manquantes, doublons).

 **Importation des librairies**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

## Chargement des datasets

In [2]:
chemin_CICIDS = '../Data/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
chemin_UNSW   = '../Data/UNSW-NB15_1.csv'
chemin_LOGS   = '../Data/cybersecurity_threat_detection_logs.csv'


df_cicids = pd.read_csv(chemin_CICIDS)
df_unsw = pd.read_csv(chemin_UNSW)
df_logs = pd.read_csv(chemin_LOGS)

/var/folders/0f/4_n58nz11g9_7f0ng4vbhl180000gq/T/ipykernel_19589/2937612983.py:7: DtypeWarning: Columns (0: 1390, 1: 53, 2: Unnamed: 47) have mixed types. Specify dtype option on import or set low_memory=False.
  df_unsw = pd.read_csv(chemin_UNSW)

## CIC-IDS-2017 : FridayWorkingHoursAfternoonDDos

In [3]:
# Dimensions
print(f'Dimensions du dataset : {df_cicids.shape[0]: } lignes et {df_cicids.shape[1]} colonnes')

Dimensions du dataset :  225745 lignes et 79 colonnes

In [4]:
print('Les 5 premières lignes :')
df_cicids.head()

Les 5 premières lignes :

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [5]:
print('Types de données par colonne :')
print(df_cicids.dtypes.value_counts())
df_cicids.dtypes

Types de données par colonne :
int64      54
float64    24
str         1
Name: count, dtype: int64

 Destination Port                int64
 Flow Duration                   int64
 Total Fwd Packets               int64
 Total Backward Packets          int64
Total Length of Fwd Packets      int64
                                ...
Idle Mean                      float64
 Idle Std                      float64
 Idle Max                        int64
 Idle Min                        int64
 Label                             str
Length: 79, dtype: object

Le dataset contient majoritairement des variables numériques.

Cela indique que la grande majorité des variables sont quantitatives, ce qui est cohérent avec des données de trafic réseau (comptage de paquets, durée, tailles, etc.)

In [6]:
# Valeurs manquantes
nombre_manquants = df_cicids.isnull().sum().sum()
print(f'Nombre de valeurs manquantes : {nombre_manquants}')

Nombre de valeurs manquantes : 4

In [7]:
# Doublons
nombre_doublons = df_cicids.duplicated().sum()
print(f'Nombre de doublons : {nombre_doublons}')

Nombre de doublons : 2633

 ## UNSW-NB15 :  UNSW-NB15_1.csv

In [11]:
# Dimensions
print(f'Dimensions du dataset : {df_unsw.shape[0]: } lignes et {df_unsw.shape[1]} colonnes')

Dimensions du dataset :  700000 lignes et 49 colonnes

In [12]:
print('Les 5 premières lignes :')
df_unsw.head()

Les 5 premières lignes :

,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0.17,3,7,1,3.1,1.1,1.2,1.3,Unnamed: 47,0.18
0,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
1,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
2,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
3,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0
4,59.166.0.0,32119,149.171.126.9,111,udp,CON,0.078339,568,312,31,...,0,2,4,2,3,1,1,2,NaN,0

In [13]:
print(' Types de données par colonne :')
print(df_unsw.dtypes.value_counts())
df_unsw.dtypes

 Types de données par colonne :
int64      31
float64    10
str         6
object      2
Name: count, dtype: int64

59.166.0.0           str
1390              object
149.171.126.6        str
53                object
udp                  str
CON                  str
0.001055         float64
132                int64
164                int64
31                 int64
29                 int64
0                  int64
0.1                int64
dns                  str
500473.9375      float64
621800.9375      float64
2                  int64
2.1                int64
0.2                int64
0.3                int64
0.4                int64
0.5                int64
66                 int64
82                 int64
0.6                int64
0.7                int64
0.8              float64
0.9              float64
1421927414         int64
1421927414.1       int64
0.017            float64
0.013            float64
0.10             float64
0.11             float64
0.12             float64
0.13               int64
0.14               int64
0.15               int64
0.16               int64
0.17               int64
3                  int64
7                  int64
1                  int64
3.1                int64
1.1                int64
1.2                int64
1.3                int64
Unnamed: 47          str
0.18               int64
dtype: object

On observe une majorité de variables numériques.

In [14]:
# Valeurs manquantes
nombre_manquants = df_unsw.isnull().sum().sum()
print(f'Nombre de valeurs manquantes : {nombre_manquants}')

Nombre de valeurs manquantes : 677785

In [30]:
# Doublons
nombre_doublons = df_unsw.duplicated().sum()
print(f'Nombre de doublons : {nombre_doublons}')

Nombre de doublons : 59209

## Cybersecurity Threat Detection Logs

In [17]:
# Dimensions
print(f' Dimensions du dataset : {df_logs.shape[0]:} lignes et {df_logs.shape[1]} colonnes')

 Dimensions du dataset : 6000000 lignes et 10 colonnes

In [16]:
print('Les 5 premières lignes :')
df_logs.head()

Les 5 premières lignes :

,timestamp,source_ip,dest_ip,protocol,action,threat_label,log_type,bytes_transferred,user_agent,request_path
0,2024-05-01T00:00:00,192.168.1.125,192.168.1.124,TCP,blocked,benign,firewall,10889,Nmap Scripting Engine,/
1,2024-07-18T00:00:00,192.168.1.201,192.168.1.201,ICMP,blocked,benign,application,36522,Nmap Scripting Engine,/
2,2024-04-07T00:00:00,192.168.1.248,192.168.1.15,HTTP,allowed,benign,application,20652,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/login
3,2024-10-26T00:00:00,192.168.1.236,192.168.1.219,HTTP,allowed,benign,application,5350,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,/login
4,2024-10-31T00:00:00,192.168.1.221,192.168.1.61,ICMP,allowed,benign,application,40691,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/

In [34]:
print('Types de données par colonne :')
print(df_logs.dtypes.value_counts())
df_logs.dtypes

Types de données par colonne :
str      9
int64    1
Name: count, dtype: int64

timestamp              str
source_ip              str
dest_ip                str
protocol               str
action                 str
threat_label           str
log_type               str
bytes_transferred    int64
user_agent             str
request_path           str
dtype: object

La majorité des variables sont donc catégorielles ou textuelles.

In [36]:
# Valeurs manquantes
nombre_manquants = df_logs.isnull().sum().sum()
print(f'Nombre de valeurs manquantes : {nombre_manquants}')

Nombre de valeurs manquantes : 0

In [35]:
# Doublons
nombre_doublons = df_logs.duplicated().sum()
print(f'Nombre de doublons : {nombre_doublons}')

Nombre de doublons : 0